### ISSUE TITLE
Measure time to get a new job (based on a new prev hash) from the JDC

### ISSUE THREAD

**Issue by GitGab19** [stratum-mining/benchmarking-tool#11]
As defined in the requirements document [here](https://github.com/stratum-mining/benchmarking-tool/blob/2e38085e3c3c7300506d80018126017010b56ffb/docs/requirements-document.md?plain=1#L107) we need to measure how much time is needed to get a new fresh job related to a new prev hash from the pool (this is the case in which a new block is found and this is of course in the case of configuration A). 

The approach that I had in mind was to leverage the library that I used to build the current [sv2-custom-proxy](https://github.com/stratum-mining/benchmarking-tool/tree/main/sv2-custom-proxy) to build specific proxies to do that. But I'm completely open to any other way and suggestions about this.

**Comment by Shourya742** [comment]
Can I take this up

**Comment by Shourya742** [comment]
Hey @GitGab19 ,
Please correct me if I'm wrong. To measure the latency for this particular setup, we will have two proxies: one between TP and JDC, and another between JDC and the Pool. For the first proxy, we will start the assessment when we receive a setNewPrevhash message from TP to JDC and end it once we receive a SetCustomMiningJobSuccess message from the Pool to JDC.

**Comment by GitGab19** [comment]
I would make it a bit different:
- the first proxy is right 
- the second one I think it should be put between translator and downstreams
  - and in this proxy I would look for the new mining.notify sent to downstreams (so that we end the measurement exactly when the new job is sent to the miner)

What do you think @Shourya742 ?

**Comment by Shourya742** [comment]
> I would make it a bit different:
> 
> * the first proxy is right
> * the second one I think it should be put between translator and downstreams
>   
>   * and in this proxy I would look for the new mining.notify sent to downstreams (so that we end the measurement exactly when the new job is sent to the miner)
> 
> What do you think @Shourya742 ?

Oh yes, I completely overlooked the downstream availability. It makes sense to point out the mining notify.

**Comment by GitGab19** [comment]
You can take the [sv1-custom-proxy](https://github.com/stratum-mining/benchmarking-tool/tree/main/sv1-custom-proxy) which counts the share as an example for that. Or maybe we should try to integrate things together (?)

**Comment by Shourya742** [comment]
> You can take the [sv1-custom-proxy](https://github.com/stratum-mining/benchmarking-tool/tree/main/sv1-custom-proxy) which counts the share as an example for that. Or maybe we should try to integrate things together (?)

Yes, sure. I have raised a PR for this. Please review and suggest any changes.

**Comment by GitGab19** [comment]
Closed by @Shourya742 in https://github.com/GitGab19/benchmarking-tool/pull/1
