### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by marathon-gary** [stratum-mining/benchmarking-tool#3]
Noting here from a discussion with @GitGab19 

More documentation would be helpful for:
What address do we mine to?

- Configure custom-configs/sri-roles/config-a/pool-config-a-docker-example.toml
- and also in jds-config-file
- JDC coinbase config is just for the solo-mining fallback system

How do we craft this address? (https://github.com/stratum-mining/stratum/tree/dev/utils/bip32-key-derivation)

- Maybe and explicit usage example would be helpful.

What network is the default that we're mining on with this config?

- testnet4

Where to change the configured address to mine to?

- Using config-a (the one with everything) you just need to change it in JDS config
- Since it will be the JDS to communicate the correct coinbase tx to JDC
- The config in Pool is needed for config-c (in which the pool builds the template and so it needs the coinbase tx)

**Comment by GitGab19** [comment]
Thank you @marathon-gary for opening it! 🙏 
Will try to address it asap

**Comment by marathon-gary** [comment]
Please add docs for defining the address for sv1 public-pool

**Comment by GitGab19** [comment]
Add docs for adjusting the `min_individual_hashrate` parameters in tProxy config

**Comment by GitGab19** [comment]
Add indication for SV1 cpu-miner: https://github.com/stratum-mining/benchmarking-tool/issues/19#issuecomment-2236152939

**Comment by GitGab19** [comment]
Address suggestion given by @pavlenex here: https://discord.com/channels/950687892169195530/1107964065936060467/1263446635195793532
