### ISSUE TITLE
Add logs exporter

### ISSUE THREAD

**Issue by GitGab19** [stratum-mining/benchmarking-tool#35]
We should ideally add a simple button in grafana to download a single .tar containing logs for every container.
This will be very useful for debugging but most importantly for assistance to first adopters of the tool

**Comment by pavlenex** [comment]
Great idea!!

**Comment by Shourya742** [comment]
Grafana Loki is an ideal candidate for this use case. We can retain logs specific to the current runtime instance and delete the rest, effectively implementing a form of rolling updates. This rolling process helps us avoid storing older runtime logs and ensures that only the current runtime logs are maintained.

**Comment by Shourya742** [comment]
Should I give it a try?

**Comment by GitGab19** [comment]
> Should I give it a try?
> 
> 

Sure!
Will assign this to you 👊
