### ISSUE TITLE
Add Default Node Connections to bitcoin.conf for Enhanced Network Connectivity

### ISSUE THREAD

**Issue by Shourya742** [stratum-mining/benchmarking-tool#43]
Add specific node addresses to `bitcoin.conf` for both `testnet4` and `mainnet` to enhance initial network connectivity. This ensures nodes connect quickly and reliably, leveraging the gossip protocol for broader network reach.

**Comment by GitGab19** [comment]
Maybe we could look at this bitcoin.conf from mempool.space: https://github.com/mempool/mempool/blob/master/production/bitcoin.conf

**Comment by GitGab19** [comment]
I reached out to `mempool.space` and they told me they are not accepting incoming connections anymore. So I thought about adding our hosted mainnet node in the `bitcoin.conf` files, but after some tests I didn't notice any difference. So I'm going to close this issue for now. A related discussion about creating an overlay network between miners can be found here: https://discord.com/channels/950687892169195530/1179824984592490496/1292920422983012383
